services:
  db:
    image: postgres:11
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=testtest0
