CREATE USER tomoya password 'tomoya' SUPERUSER CREATEDB CREATEROLE LOGIN;
CREATE DATABASE customer OWNER tomoya;
CREATE DATABASE user1 OWNER tomoya;
CREATE DATABASE user2 OWNER tomoya;
CREATE DATABASE user3 OWNER tomoya;
